version: "3"
services: 
  mongodb-server:
    image: 'mongo:3.6.20-xenial'
    restart: always
    container_name: 'my-mongo'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - /home/independentchen/mongo/data:/data/db
    ports:
      - 27017:27017

