version: "3"
services: 
  mongodb-server:
    image: 'mongo:3.6.20-xenial'
    restart: always
    container_name: 'my-mongo'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REGULAR_USER: ${MONGO_REGULAR_USER}
      MONGO_REGULAR_PASSWORD: ${MONGO_REGULAR_PASSWORD}
      MONGO_REGULAR_DATABASE: ${MONGO_REGULAR_DATABASE}
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ['--auth']
    ports:
      - 27017:27017

