version: "3"
services: 
  mongodb-server:
    build: .
    restart: always
    ports:
      - 27017:27017
    container_name: 'my-mongo'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REGULAR_USER: ${MONGO_REGULAR_USER}
      MONGO_REGULAR_PASSWORD: ${MONGO_REGULAR_PASSWORD}
      MONGO_REGULAR_DATABASE: ${MONGO_REGULAR_DATABASE}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongodata:/data/db

volumes:
  mongodata:
    driver_opts:
      type: none
      device: ./db
      o: bind